// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter/services.dart' show appFlavor;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        // iOS development and automated testing use the isolated Dev app.
        // Production must be selected explicitly with `--flavor prod`.
        return appFlavor == 'prod' ? iosProd : iosDev;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGlxMOZdc9D6Nz61gC5dNAkicOfANzBpI',
    appId: '1:77063889783:android:5f20ccec814dddeeea3772',
    messagingSenderId: '77063889783',
    projectId: 'labaan-f3fa6',
    storageBucket: 'labaan-f3fa6.firebasestorage.app',
  );
  static const FirebaseOptions iosProd = FirebaseOptions(
    apiKey: 'AIzaSyDJj0iadfqI4Q6CPBB0-tCuRSniS7DPoR0',
    appId: '1:77063889783:ios:c5cdc597f01c4282ea3772',
    messagingSenderId: '77063889783',
    projectId: 'labaan-f3fa6',
    storageBucket: 'labaan-f3fa6.firebasestorage.app',
    androidClientId:
        '77063889783-k2k3aqckvhadud1bbdhcp34s6etjpb3p.apps.googleusercontent.com',
    iosClientId:
        '77063889783-tg4v4tj34jenskjt4gfprelvmdihdh1t.apps.googleusercontent.com',
    iosBundleId: 'com.labaan.labaan',
  );
  static const FirebaseOptions iosDev = FirebaseOptions(
    apiKey: 'AIzaSyDJj0iadfqI4Q6CPBB0-tCuRSniS7DPoR0',
    appId: '1:77063889783:ios:c5cf4601ed1cfd63ea3772',
    messagingSenderId: '77063889783',
    projectId: 'labaan-f3fa6',
    storageBucket: 'labaan-f3fa6.firebasestorage.app',
    androidClientId:
        '77063889783-k2k3aqckvhadud1bbdhcp34s6etjpb3p.apps.googleusercontent.com',
    iosClientId:
        '77063889783-bofu9melt68uqai6r27ai3au6ph0g8gg.apps.googleusercontent.com',
    iosBundleId: 'com.labaan.labaan-dev',
  );
}
